### ISSUE TITLE
Roadmap 3D

### ISSUE THREAD

**Issue by GrumpyLion** [amzeratul/halley#120]
This list is not final and will grow as I'm working on the 3d features

List is kinda sorted by importance
- [x] Add GLTF importer (since it's kinda the standard and works pretty good for models and animations, also open source)
This works good enough for now. Need to check .glb with textures again at some point, but imports meshes now correctly.  
- [ ] Add mesh optimizer for improving vertex caching etc (https://github.com/zeux/meshoptimizer)
- [x] Add mesh viewer for asset prevewing
- [ ] Add mesh component 
- [ ] Add 3D Transform component
- [ ] Add 3D Camera component
