### ISSUE TITLE
Roadmap Vulkan

### ISSUE THREAD

**Issue by GrumpyLion** [amzeratul/halley#121]
- [ ] Initialize vulkan fully (intance, debug, device, swapchain renderpasses etc etc..)
- [ ] Set up buffers correctly with VMA
- [ ] Set up renderpasses for rendering
- [ ] Sprite rendering
- [ ] Editor rendering
- [ ] Improve performance?
